-- Torna campos de endereço do USUARIO opcionais
ALTER TABLE usuario ALTER COLUMN rua DROP NOT NULL;
ALTER TABLE usuario ALTER COLUMN bairro DROP NOT NULL;
ALTER TABLE usuario ALTER COLUMN numero DROP NOT NULL;
ALTER TABLE usuario ALTER COLUMN cidade DROP NOT NULL;
ALTER TABLE usuario ALTER COLUMN cep DROP NOT NULL;
ALTER TABLE usuario ALTER COLUMN estado DROP NOT NULL;

-- Opcionalmente, também flexibilizar para PROFISSIONAL
ALTER TABLE profissional ALTER COLUMN rua DROP NOT NULL;
ALTER TABLE profissional ALTER COLUMN bairro DROP NOT NULL;
ALTER TABLE profissional ALTER COLUMN numero DROP NOT NULL;
ALTER TABLE profissional ALTER COLUMN cidade DROP NOT NULL;
ALTER TABLE profissional ALTER COLUMN cep DROP NOT NULL;
ALTER TABLE profissional ALTER COLUMN estado DROP NOT NULL;
